server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
          - Path= /users/**
        - id: service-movie
          uri: lb://service-movie
          predicates:
          - Path= /movies/**
        - id: service-booking
          uri: lb://service-booking
          predicates:
          - Path= /bookings/**
        - id: service-showtime
          uri: lb://service-showtime
          predicates:
          - Path= /showtimes/**
# spring:
#   application:
#     name: service-shopping
#   h2:
#     console:
#       enabled: true
#   datasource:
#     url: jdbc:h2:mem:shoppingBD;
#     driver-class-name: org.h2.Driver
#     platform: h2
#     username: sa
#     password:
#   jpa:
#     show-sql: true
#     database-platform: org.hibernate.dialect.H2Dialect
# feign:
#   hystrix:
#     enabled: true